//! Auto-generated `CoW` Protocol orderbook API client.
//!
//! **Do not edit this file manually.** It is generated by
//! [`progenitor`](https://crates.io/crates/progenitor) from the `OpenAPI` spec
//! at `specs/orderbook-api.yml` via `build.rs`.
//!
//! This module exposes a low-level, spec-faithful HTTP client ([`Client`]) and
//! all request/response types (in the [`types`] submodule) exactly as defined
//! in the upstream specification. It is primarily an authoritative mirror of
//! the spec: building this crate fails if the upstream `OpenAPI` document
//! drifts in a way `progenitor` cannot model.
//!
//! The high-level [`super::api::OrderBookApi`] client is currently a
//! hand-written `reqwest` wrapper and does **not** yet delegate to the
//! generated [`Client`]. Rewiring it is tracked separately; for now the
//! generated module is re-exported so consumers can drop down to the
//! spec-faithful client when the hand-written API lacks an endpoint.

#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    missing_docs,
    unreachable_pub,
    unused_qualifications,
    elided_lifetimes_in_paths,
    redundant_imports,
    rustdoc::all,
    reason = "progenitor output does not conform to the workspace lint profile \
              and cannot be fixed without patching the upstream generator"
)]
mod inner {
    include!(concat!(env!("OUT_DIR"), "/orderbook_generated.rs"));
}

pub use inner::*;
