//! Auto-generated `CoW` Protocol orderbook API client.
//!
//! **Do not edit this file manually.** It is generated by
//! [`progenitor`](https://crates.io/crates/progenitor) from the OpenAPI spec
//! at `specs/orderbook-api.yml` via `build.rs`.
//!
//! This module exposes a low-level, spec-faithful HTTP client ([`Client`]) and
//! all request/response types (in the [`types`] submodule) exactly as defined
//! in the upstream specification.
//!
//! Higher-level ergonomics live in [`super::api::OrderBookApi`], which wraps
//! this generated client and converts between generated string-based types and
//! our domain types (`alloy_primitives::Address`, `U256`, etc.).

// Silence lints on generated code — the generator's output does not conform
// to our strict workspace lint profile.
#[allow(
    // The upstream spec has inconsistent naming we can't control.
    clippy::all,
    clippy::doc_markdown,
    clippy::missing_const_for_fn,
    clippy::must_use_candidate,
    clippy::str_to_string,
    clippy::shadow_reuse,
    // Restriction lints denied at workspace level — progenitor output uses
    // unwrap/expect in infallible contexts (e.g. URL parsing of known-good
    // literals). `clippy::all` does not cover restriction lints.
    clippy::unwrap_used,
    clippy::expect_used,
    missing_docs,
    unreachable_pub,
    unused_qualifications,
    elided_lifetimes_in_paths,
    redundant_imports,
)]
mod inner {
    include!(concat!(env!("OUT_DIR"), "/orderbook_generated.rs"));
}

pub use inner::*;
