#![allow(
    clippy::allow_attributes_without_reason,
    clippy::disallowed_macros,
    clippy::print_stdout,
    clippy::disallowed_methods,
    clippy::uninlined_format_args,
    clippy::literal_string_with_formatting_args,
    clippy::doc_markdown,
    clippy::type_complexity,
    clippy::map_err_ignore,
    clippy::missing_assert_message,
    clippy::single_match_else,
    clippy::print_literal
)]
//! # App-Data: Metadata Encoding
//!
//! Demonstrates how to build, hash, validate, and convert CoW Protocol
//! order metadata (app-data).
//!
//! App-data is a JSON document that encodes intent metadata (referrer, UTM,
//! hooks, partner fees, etc.) into a `bytes32` keccak256 hash stored on-chain.
//! The full JSON is pinned to IPFS, and only the hash goes into the order.
//!
//! This is the Rust equivalent of:
//!
//! ```ts
//! import { MetadataApi } from '@cowprotocol/app-data';
//! const api = new MetadataApi();
//! const doc = await api.generateAppDataDoc({ ... });
//! const { appDataHex, appDataContent } = await api.appDataToCid(doc);
//! ```
//!
//! ## Usage
//!
//! ```sh
//! cargo run --example app_data
//! ```

use cow_app_data::{
    AppDataDoc, Metadata, MetadataApi, OrderInteractionHooks, PartnerFee, PartnerFeeEntry, Quote,
    Referrer, Utm, appdata_hex, appdata_hex_to_cid, cid_to_appdata_hex, stringify_deterministic,
    validate_app_data_doc,
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // ── 1. Build an app-data document ────────────────────────────────────────
    //
    // Start from a template generated by MetadataApi and customise it.
    let api = MetadataApi::new();
    let mut doc = api.generate_app_data_doc("CowRsAppDataExample");

    // Populate metadata — these fields are all optional.
    doc.metadata = Metadata {
        referrer: Some(Referrer::code("COWRS-REFERRAL")),
        utm: Some(Utm {
            utm_source: Some("cow-rs-example".to_owned()),
            utm_medium: Some("sdk".to_owned()),
            utm_campaign: None,
            utm_content: None,
            utm_term: None,
        }),
        quote: Some(Quote {
            slippage_bips: 50, // 0.5%
            smart_slippage: None,
        }),
        hooks: Some(OrderInteractionHooks::new(vec![], vec![])),
        partner_fee: Some(PartnerFee::single(PartnerFeeEntry {
            volume_bps: Some(25), // 0.25% volume fee
            surplus_bps: None,
            price_improvement_bps: None,
            max_volume_bps: None,
            recipient: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045".to_owned(),
        })),
        ..Default::default()
    };

    println!("=== App-Data Document ===");
    println!();

    // ── 2. Canonical JSON (deterministic serialization) ──────────────────────
    //
    // The JSON is serialised with sorted keys so the keccak256 hash is
    // deterministic regardless of field insertion order.
    let json = stringify_deterministic(&doc)?;
    println!("Canonical JSON:");
    println!("  {json}");
    println!();

    // ── 3. Keccak256 hash ────────────────────────────────────────────────────
    //
    // This is the `bytes32` value you put in the `appData` field of the order.
    let hash = appdata_hex(&doc)?;
    let hash_hex = format!("0x{}", alloy_primitives::hex::encode(hash.as_slice()));
    println!("App-data hash (bytes32):");
    println!("  {hash_hex}");
    println!();

    // ── 4. Validate against the JSON schema ──────────────────────────────────
    let validation = validate_app_data_doc(&doc);
    println!("Schema validation: {validation}");
    println!();

    // ── 5. CID conversion (hex ↔ IPFS CID v1) ───────────────────────────────
    //
    // The app-data hash can be converted to an IPFS CID v1 for pinning,
    // and converted back to verify the round-trip.
    let cid = appdata_hex_to_cid(&hash_hex)?;
    println!("IPFS CID v1:   {cid}");

    let roundtrip = cid_to_appdata_hex(&cid)?;
    println!("Roundtrip hex: {roundtrip}");
    assert_eq!(hash_hex, roundtrip, "CID round-trip mismatch");
    println!("  (round-trip OK)");
    println!();

    // ── 6. Using the MetadataApi facade ──────────────────────────────────────
    //
    // `get_app_data_info` computes hash, CID, and canonical JSON in one call.
    let info = api.get_app_data_info(&doc)?;
    println!("Full app-data info:");
    println!("  CID:     {}", info.cid);
    println!("  Hex:     {}", info.app_data_hex);
    println!("  Content: {}", info.app_data_content);
    println!();

    // ── 7. Minimal document (no metadata) ────────────────────────────────────
    let minimal = AppDataDoc {
        version: "1.1.0".to_owned(),
        app_code: Some("MinimalExample".to_owned()),
        environment: None,
        metadata: Metadata::default(),
    };
    let minimal_hash = appdata_hex(&minimal)?;
    println!("Minimal app-data hash: 0x{}", alloy_primitives::hex::encode(minimal_hash.as_slice()));

    Ok(())
}
